version: '3.8'

services:
  db:
    image: postgres:15
    container_name: stoiccapital_db
    restart: always
    environment:
      POSTGRES_USER: stoic_user
      POSTGRES_PASSWORD: stoic_password
      POSTGRES_DB: stoiccapital
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: