version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: stoic_capital_final
      POSTGRES_USER: stoic-capital-admin
      POSTGRES_PASSWORD: stoic-capital-admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
