# Generated by Django 4.2.19 on 2025-03-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TradeInstrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("futures", "Futures"),
                            ("stock", "Stock"),
                            ("cfd", "CFD"),
                            ("currency", "Currency"),
                            ("crypto", "Crypto"),
                        ],
                        default="futures",
                        max_length=10,
                    ),
                ),
                ("tick_size", models.DecimalField(decimal_places=6, max_digits=10)),
                ("tick_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contract_size", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
