# Generated by Django 4.2.19 on 2025-03-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradingaccount",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
